description: >
  skw executor cimg/openjdk image
docker:
  - image: cimg/openjdk:<<parameters.tag>>'
parameters:
  tag:
    default: "11.0"
    description: >
      Pick a specific circleci/openjdk image variant:
      https://hub.docker.com/r/cimg/openjdk/tags
    type: string
